(()=>{const c=document.getElementById('game'),x=c.getContext('2d'),W=c.width,H=c.height,G=440,$=id=>document.getElementById(id);let k={},p,obs,items,foes,hp,t,coins,elapsed,active,pause,boost,invuln,attackEnd,won,last=0;
function reset(){p={x:70,y:G-60,w:38,h:60,vy:0,ground:true,dir:1};obs=[];items=[];foes=[];for(let a=280;a<5400;a+=250){obs.push({x:a+Math.random()*50,w:30+Math.random()*25,type:Math.random()<.65?'rock':'mud'});if(Math.random()<.85)items.push({x:a+85,y:G-65-Math.random()*70,type:'coin',got:false});if(Math.random()<.3)items.push({x:a+145,y:G-32,type:Math.random()<.5?'bread':'potion',got:false});if(Math.random()<.5)foes.push({x:a+170,y:G-40,w:32,h:40,dir:-1,alive:true})}hp=3;t=180;coins=0;elapsed=0;boost=0;invuln=0;attackEnd=0;active=false;pause=false;won=false;sync()}
function start(){if(won||hp<=0||t<=0)reset();active=true;pause=false;$('overlay').classList.remove('show');last=performance.now()}
function finish(win){active=false;won=win;$('msgTitle').textContent=win?'Замок достигнут!':'Поход окончен';$('msgText').textContent=win?'Слава рыцарю! Монет собрано: '+coins+'. Святой кубок ждёт у ворот.':'Монет собрано: '+coins+'. Попробуй новый поход.';$('startBtn').textContent='Новый поход';$('overlay').classList.add('show')}
function jump(){if(active&&!pause&&p.ground){p.vy=-640;p.ground=false}}function attack(){if(active&&!pause)attackEnd=elapsed+.25}
function hold(id,key){let e=$(id);e.addEventListener('pointerdown',v=>{v.preventDefault();k[key]=true});['pointerup','pointerleave','pointercancel'].forEach(n=>e.addEventListener(n,()=>k[key]=false))}
hold('leftBtn','ArrowLeft');hold('rightBtn','ArrowRight');$('jumpBtn').onpointerdown=e=>{e.preventDefault();jump()};$('attackBtn').onpointerdown=e=>{e.preventDefault();attack()};window.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp',' '].includes(e.key))e.preventDefault();k[e.key]=true;if(e.key==='ArrowUp')jump();if(e.key===' ')attack();if(e.key.toLowerCase()==='p'&&active)pause=!pause;if(e.key.toLowerCase()==='r'){reset();start()}});window.addEventListener('keyup',e=>k[e.key]=false);$('startBtn').onclick=start;$('restartBtn').onclick=()=>{reset();start()};$('pauseBtn').onclick=()=>{if(active)pause=!pause;else start()};
function hit(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}function sync(){$('hearts').textContent=[0,1,2].map(i=>i<hp?'♥':'♡').join(' ');$('coins').textContent=coins;$('timer').textContent=t;$('boost').textContent=boost>elapsed?Math.ceil(boost-elapsed)+'с':'—'}
function update(dt){if(!active||pause)return;elapsed+=dt;t=Math.max(0,180-Math.floor(elapsed));if(!t){sync();finish(false);return}let d=(k.ArrowRight?1:0)-(k.ArrowLeft?1:0);if(d)p.dir=d;p.x=Math.max(0,p.x+d*(boost>elapsed?340:170)*dt);p.vy+=1450*dt;p.y+=p.vy*dt;if(p.y+p.h>=G){p.y=G-p.h;p.vy=0;p.ground=true}
for(let f of foes){if(!f.alive)continue;f.x+=f.dir*48*dt;if(f.x<p.x-100)f.dir=1;if(f.x>p.x+700)f.dir=-1;if(elapsed<attackEnd&&Math.abs(f.x-(p.x+p.dir*45))<55){f.alive=false;coins+=2}else if(hit(p,f)&&elapsed>invuln){hp--;invuln=elapsed+1.1;p.x-=p.dir*30;if(hp<=0){sync();finish(false);return}}}
for(let o of obs){if(o.type==='rock'&&hit(p,{x:o.x,y:G-30,w:o.w,h:30})&&p.y+p.h>G-31&&elapsed>invuln){hp--;invuln=elapsed+1;p.x-=p.dir*25;if(hp<=0){sync();finish(false);return}}}
let slow=obs.some(o=>o.type==='mud'&&p.x+p.w>o.x&&p.x<o.x+o.w&&p.y+p.h>G-12);if(slow)p.x-=d*75*dt;
for(let i of items)if(!i.got&&hit(p,{x:i.x,y:i.y,w:23,h:23})){i.got=true;if(i.type==='coin')coins++;if(i.type==='bread')hp=Math.min(3,hp+1);if(i.type==='potion')boost=elapsed+5}
if(p.x>5200){sync();finish(true)}sync()}
function draw(){x.clearRect(0,0,W,H);let cam=Math.max(0,Math.min(4350,p.x-180)),sky=x.createLinearGradient(0,0,0,H);sky.addColorStop(0,'#77b4c9');sky.addColorStop(1,'#f3d6a0');x.fillStyle=sky;x.fillRect(0,0,W,H);
x.fillStyle='#fff0cfaa';for(let i=0;i<7;i++){let a=((i*190-elapsed*8)%(W+120)+W+120)%(W+120)-60,b=50+i%3*45;x.beginPath();x.arc(a,b,22,0,7);x.arc(a+25,b-9,28,0,7);x.arc(a+52,b,19,0,7);x.fill()}
for(let l=0;l<2;l++){x.fillStyle=l?'#71845a':'#9ba76c';x.beginPath();x.moveTo(0,G);for(let a=0;a<=W+20;a+=20)x.lineTo(a,330+l*42+Math.sin((a+cam*(l?.22:.12))/95)*27);x.lineTo(W,G);x.fill()}
let castle=750-cam*.32;x.fillStyle='#6c6253';x.fillRect(castle,235,150,205);x.fillRect(castle-18,215,48,225);x.fillRect(castle+120,210,48,230);x.fillStyle='#4c463e';for(let a=castle-18;a<castle+170;a+=24)x.fillRect(a,205,13,14);x.fillStyle='#9b3328';x.beginPath();x.moveTo(castle-25,215);x.lineTo(castle+6,170);x.lineTo(castle+37,215);x.fill();x.beginPath();x.moveTo(castle+112,210);x.lineTo(castle+144,164);x.lineTo(castle+177,210);x.fill();
x.fillStyle='#4c5839';x.fillRect(0,G,W,H-G);x.fillStyle='#849257';x.fillRect(0,G,W,10);
for(let o of obs){let a=o.x-cam;if(a<-60||a>W+60)continue;if(o.type==='rock'){x.fillStyle='#716b60';x.beginPath();x.moveTo(a,G);x.lineTo(a+6,G-25);x.lineTo(a+o.w*.55,G-38);x.lineTo(a+o.w,G-10);x.fill()}else{x.fillStyle='#34251e';x.beginPath();x.ellipse(a+o.w/2,G-3,o.w/2,9,0,0,7);x.fill()}}
for(let i of items){if(i.got)continue;let a=i.x-cam;if(a<-30||a>W+30)continue;if(i.type==='coin'){x.fillStyle='#d4af37';x.beginPath();x.arc(a+11,i.y+11,10,0,7);x.fill();x.strokeStyle='#fff0a2';x.stroke()}else{x.fillStyle=i.type==='bread'?'#c28a4d':'#b03b46';x.fillRect(a+5,i.y+4,14,19);x.fillStyle='#f1d89b';x.fillRect(a+8,i.y,8,6)}}
for(let f of foes){if(!f.alive)continue;let a=f.x-cam;if(a<-50||a>W+50)continue;x.fillStyle='#496b3c';x.fillRect(a+5,f.y+10,23,32);x.beginPath();x.arc(a+16,f.y+11,13,0,7);x.fill();x.fillStyle='#f3e4ad';x.fillRect(a+8,f.y+8,5,5);x.fillRect(a+20,f.y+8,5,5)}
let a=p.x-cam,b=p.y;x.save();if(p.dir<0){x.translate(a*2+p.w,0);x.scale(-1,1);a=p.x-cam}if(elapsed<invuln&&Math.floor(elapsed*14)%2===0)x.globalAlpha=.35;x.fillStyle='#263239';x.fillRect(a+8,b+28,9,29);x.fillRect(a+23,b+28,9,29);x.fillStyle='#aab9b9';x.fillRect(a+5,b+12,29,26);x.fillStyle='#6c7c80';x.fillRect(a+8,b+15,23,16);x.fillStyle='#cbd1c8';x.fillRect(a+8,b,24,22);x.fillStyle='#36454a';x.fillRect(a+10,b+6,21,7);x.fillStyle='#e2ba58';x.fillRect(a+19,b+9,11,3);x.fillStyle='#d5d9ce';x.fillRect(a+32,b+25,elapsed<attackEnd?35:4,4);x.fillStyle='#76532e';x.fillRect(a+8,b+56,12,6);x.fillRect(a+23,b+56,12,6);x.restore();x.fillStyle='#2c261c';x.font='bold 17px serif';x.fillText('К ЗАМКУ →',W-140,35);if(pause){x.fillStyle='#20150fbb';x.fillRect(0,0,W,H);x.fillStyle='#f2dfb3';x.font='38px serif';x.fillText('ПАУЗА',W/2-55,H/2)}}
function loop(now){let dt=Math.min(.04,(now-(last||now))/1000);last=now;update(dt);draw();requestAnimationFrame(loop)}reset();requestAnimationFrame(loop)})();